### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by gleporeNARA** [perrinjerome/mitene_download#1]
First media block in JSON below.

python -m mitene_download https://mitene.us/f/jhv8sXksxkE

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lepore/.local/lib/python3.8/site-packages/mitene_download.py", line 71, in <module>
    main()
  File "/home/lepore/.local/lib/python3.8/site-packages/mitene_download.py", line 39, in main
    page_text = r.text.split("//<![CDATA[\nwindow.gon={};gon.media=")[1].split(";gon.familyUserIdToColorMap=")[0]
IndexError: list index out of range

{"id":5580213305,"uuid":"166D63BD-F007-4E73-8D7B-DACE35B1A7B0","userId":"210072416893","mediaType":"movie","originalHash":"1B4C72A7-61FE-48D6-9F1D-549EE881DD48/L0/001","hasComment":false,"comments":[],"footprints":[],"tookAt":"2021-11-01T05:35:18+09:00","audienceType":"family","mediaWidth":540,"mediaHeight":960,"mediaOrientation":90,"latitude":0.0,"longitude":0.0,"mediaDeviceModel":"iPhone12,1","deviceFilePath":"1B4C72A7-61FE-48D6-9F1D-549EE881DD48/L0/001","videoDuration":12643,"contentType":"video/mp4","origin":"upload","thumbnailGenerated":true,"expiringUrl":"https://media-files-production-cdn.mitene.us/media/uploads/large/166D63BD-F007-4E73-8D7B-DACE35B1A7B0.jpg?p=1635713351\u0026Expires=1635775167\u0026Signature=ChLwt54SzmenpJkGm6Q4QdoO49vSUIJHEFY7rBlftBqk1xvhlKQ31A4FBYUYS1kR4TqQwNZNMfFx4PY7M6QlykF~feL6jNmuQm0cX6Cr1x-qjlVqurYyaNVzVgJFCIvBNEX6Z33tneHIDRbtQn11xgsz4bN3LcF4sGiADW5zVz~encNHaU0Yn8fNMpqbZ0f2flBT4Ae6F-g58V~wBqssE~XQanE-8R5LgF6KSWw57XPCuPh2tdvUD2vVbskZAOGnnPaHC5pt5TLF0jNNCCuiUQV5Q8gkk9WpozIb1W2X6TJ7X94AFP3oPJU~Kue0y1re3qMIUjMMqIbQPEpszQx~oA__\u0026Key-Pair-Id=APKAJL6OCBMEEECHRPSQ","expiringVideoUrl":"https://media-files-production-cdn.mitene.us/media/uploads/smartphone/166D63BD-F007-4E73-8D7B-DACE35B1A7B0.mp4?p=1635713351\u0026Expires=1635775167\u0026Signature=OUcDVLieVOlbmsTN1tNS5VnIo59W7iPsrjWF7ysl84hTe5X6gcg5IUMc74Q2rMbPkIEs8w58M0nahXJBafCg6TnMefaPU-gd6g1b-vr6k72Ep0NP3BAjUJRzoIjWhJJZLfpoqSsC6b~bFOXrvrmCUtSVB25oEaGNYeN70EpcFrzS~kKB4GFIleXLzYaitIhsOr-7PV-w0BKVsicALbWLY360vR0QOtMI28zZ1gJEH5ryV7cCcy1pgMzUE4Y5fPySP747H3-qB51O~fwat-Ypipy8yjJZCr629Ck-~SliImFikY5dqGGObaQi07JRay84TZpqJeo24mg8PZbJE3ac6A__\u0026Key-Pair-Id=APKAJL6OCBMEEECHRPSQ","expiringThumbUrl":"https://media-files-production-cdn.mitene.us/media/uploads/small/166D63BD-F007-4E73-8D7B-DACE35B1A7B0.jpg?p=1635713351\u0026Expires=1635775167\u0026Signature=I4cb4V773WS4oz1DqL57dJLWv5YqKHq1kkzC7vXLyysPoOsKTP0r1OH6lJYDRFB~W4hV6g7XzT4zuctUbWrPI15wMBC2r9-PGFvx05kXn3ZnG55Q-voh~wxwOjnXvADEcMQm-Xdz414IofD1Lwld~qNA-EGwR3CQB~sLyhwjql-iIrVEaHmo-JhtmwA2Rj7Ao0ELjVvDn1Br2f2uT4HLMAxVFIF1gxuUDd9FdE7yU35uDtOUIFqIvbm0QHSbXkZchJO3kwBI5C9dj0XI44OdmNVqnFRu0kj0qmAI5iJtPOezg8BymjMebE6Ai6CmoByA8tArXQ-KU-dSUUVBMRI5Ag__\u0026Key-Pair-Id=APKAJL6OCBMEEECHRPSQ"}

**Comment by gleporeNARA** [comment]
Probably something different between a Private album and a Public album.

**Comment by perrinjerome** [comment]
Ah yes, only public albums are supported at the moment. It might be possible to support password protected albums, I'll take a look thanks !

**Comment by perrinjerome** [comment]
I just made a version 0.0.2 with support for password protected albums, let me know if that fixed this issue.

**Comment by gleporeNARA** [comment]
That fixed it! Thanks. The only other suggestions I would make would be to think about implementing parallel downloading capability (although that's probably pretty tricky) and to offer the ability to rename the files to remove the hash-looking characters (i.e. 2021-07-15T02:03:36+09:00-0FEB62C4-69B5-4171-AC0F-61211772BFBD.jpeg to 2021-07-15-image1.jpeg).

Thanks!

**Comment by gleporeNARA** [comment]
Oh, and possibly the ability to specify a date range, or a --refresh switch that only downloads images that haven't been previously downloaded.
