### ISSUE TITLE
Errno 22 & Coroutine 'download_media' was never awaited

### ISSUE THREAD

**Issue by Jeathead** [perrinjerome/mitene_download#11]
Hi Jerome,

Am trying to run this script and I keep running into issues with the following:

OSError: [Errno 22] Invalid argument: 'out\\2024-03-21T02:52:52+09:00-3230BB5A-F34E-4C78-BB3B-6A2BE8759E01.md.tmp'
sys:1: RuntimeWarning: coroutine 'download_media' was never awaited

Do you have a suggestion to correct this error? It would really be appreciated, I have close to 0 python experience

**Comment by perrinjerome** [comment]
Hi, is it when running on windows ?

I did not try on windows, this error message looks like  such a filename is not allowed.

**Comment by Jeathead** [comment]
It is on Windows, I've never used Linux personally. Do you think there is a
workaround?

**Comment by perrinjerome** [comment]
Thanks for confirmation. I'll try later, it's highly possible that this version does not work at all on windows, but it might be easy to fix.

**Comment by Jeathead** [comment]
Thanks so much! Would be an absolute lifesaver

**Comment by perrinjerome** [comment]
@Jeathead can you easily try the changes from https://github.com/perrinjerome/mitene_download/pull/12 ? thanks

**Comment by the-potemkin** [comment]
@perrinjerome 
I was following this thread and had same issues since same win11 environment.
The  __version__ = '0.2.1' has this error now.
```
File "C:\py\mitene_download.py", line 140, in async_main
    comment_f.write(
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-3: character maps to <undefined>
sys:1: RuntimeWarning: coroutine 'download_media' was never awaited
```
your help is appreciated., Thank you!

**Comment by perrinjerome** [comment]
Thanks, so it means that the "Errno 22" was about ":" in filenames. I think I understood the problem with encoding. I will upload a release that should fix this.

**Comment by perrinjerome** [comment]
https://pypi.org/project/mitene_download/0.2.1/ let me know if you still notice something wrong, thanks !

**Comment by the-potemkin** [comment]
@perrinjerome it works!  thank you x 1000 !

**Comment by perrinjerome** [comment]
Great, thank you for confirming
