### ISSUE TITLE
[feature-request] Only download media from timestamp

### ISSUE THREAD

**Issue by cuong-dang** [perrinjerome/mitene_download#13]
Hi, could we have the option to only download media that were added since a certain timestamp? I would like to periodically backup my library; so it'd be great not to have to download everything each time.

**Comment by perrinjerome** [comment]
Hi, running periodically to backup is the primary use case, when running a second time, the program detects already downloaded medias and only download new - so it's already more or less doing what you expect here.

**Comment by cuong-dang** [comment]
@perrinjerome Looks like it's still downloading all comments every time. Could you add the same check for comments as well?

Edit: I created a PR for this: https://github.com/perrinjerome/mitene_download/pull/14
