### ISSUE TITLE
Script did not create out folder

### ISSUE THREAD

**Issue by jsavage** [perrinjerome/mitene_download#5]
Minor issue but found that the script did not create the out folder.  This was on python 3.9.2
I created the folder out manually and widened permissions for this folder and the script then ran but it would be good to resolve this.

**Comment by perrinjerome** [comment]
This code creates the folder:

https://github.com/perrinjerome/mitene_download/blob/5e77af9ba9fa5f39245a84169531565330642847/mitene_download.py#L67

from what you describe, the problem you experienced might be that you ran the script in a folder where the user does not have the permission, then you create the folder with sudo. If that was something like that, I don't really think there's anything we can do in mitene_download for this.
